#!/bin/bash

set -o errexit

export GIT_AUTHOR_NAME="John Doe"
export GIT_AUTHOR_EMAIL="noreply@example.net"
export GIT_COMMITTER_NAME="John Doe"
export GIT_COMMITTER_EMAIL="noreply@example.net"

if [ ! -d .git ]; then
    git init
fi

if ! grep -q -F -e "$GIT_COMMITTER_EMAIL" .git/config; then
    git config user.name "$GIT_COMMITTER_NAME"
    git config user.email "$GIT_COMMITTER_EMAIL"
fi

if [ ! -f .gitignore ]; then
    export GIT_AUTHOR_DATE="1343462400 +0400"
    export GIT_COMMITTER_DATE="1343462400 +0400"
    touch .gitignore
    git add .gitignore
    git commit -m 'Initial commit' .gitignore
fi

for dir in "$@"; do
    for fname in $(ls -tr "$dir/"); do
        rm -f dump.xml dump.xml.sig manifest
        unzip "$dir/$fname"
        files="dump.xml dump.xml.sig $dir/$fname"

        updateXXX=$(head -c 4096 dump.xml | grep -o '\(\<updateTimeUrgently="[^"]*"\|updateTime="[^"]*"\)' | sed 's,updateTime=",updateTime ,; s,updateTimeUrgently=",updateTimeUrgently ,; s,"$,,';)

        meta=$({
            TZ=UTC stat --format='mtime %Y %y %n' $files | sed 's,\.000000000 , ,g';
            md5sum $files | sed 's,^,MD5 ,';
            sha1sum $files | sed 's,^,SHA1 ,';
            sha256sum $files | sed 's,^,SHA256 ,';
            sha512sum $files | sed 's,^,SHA512 ,';
            echo "$updateXXX"
        } | sed "s|$dir/$fname|dump.zip|g")
        echo "$meta" >manifest

        export GIT_AUTHOR_NAME=$(echo -e $(openssl pkcs7 -in dump.xml.sig -inform DER -print_certs | grep ^subject= | tr '/' '\n' | grep ^CN=))
        export GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"
        export GIT_AUTHOR_EMAIL="noreply@example.org"
        export GIT_COMMITTER_EMAIL="${GIT_AUTHOR_EMAIL}"
        export GIT_AUTHOR_DATE=$(stat --format="%Y +0000" dump.xml)
        export GIT_COMMITTER_DATE=$(stat --format="%Y +0000" dump.xml.sig)

        subj=$(echo "$updateXXX" | awk 'BEGIN { ut = ""; utu = "" } ($1 == "updateTime") {ut = $2;} ($1 == "updateTimeUrgently") {utu = $2;} END { if (ut && utu) { print ut, "/", utu } else if (ut && !utu) { print ut, "(updateTime)"} else if (!ut && utu) { print utu, "(updateTimeUrgently)" } else {print "WAT?"} }')

        git add dump.xml dump.xml.sig manifest
        git commit -m "$subj" -m "$meta" dump.xml dump.xml.sig manifest

        read size _ < <(du --bytes -sc .git/objects/?? | awk '($2 == "total") {print $1}')
        if [ $size -gt $(( 1024 * 1024 * 1024 )) ]; then
            git gc
        fi
    done
done

git gc
