#!/usr/bin/env python3

import xml.parsers.expat
import sys

# 3 handler functions
def start_element(name, attrs):
    pass # print('Start element:', name, attrs, p.CurrentByteIndex)
def end_element(name):
    pass # print('End element:', name, p.CurrentByteIndex)
def char_data(data):
    pass # print('Character data:', repr(data), p.CurrentByteIndex)

p = xml.parsers.expat.ParserCreate()

p.StartElementHandler = start_element
p.EndElementHandler = end_element
p.CharacterDataHandler = char_data

with open(sys.argv[1], 'rb') as fd:
    p.ParseFile(fd)
